services:
  imap-to-papra:
    image: ghcr.io/slightlyuselesscreations/imap-to-papra:latest
    container_name: imap-to-papra
    restart: unless-stopped

    env_file:
      - .env

    environment:
      CRON_SCHEDULE: "*/5 * * * *"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
